### ISSUE TITLE
Dockerfile?

### ISSUE THREAD

**Issue by zoobab** [hypriot/rpi-kernel#11]
Hi,

There is a Dockerfile here for another version of rpi-kernel:

https://hub.docker.com/r/maiome/rpi-kernel-build/~/dockerfile/

Could you provide one for this project? The place where I want to build the kernel does not have the permission to load a kernel module for Vagrant. And with docker there is no emulation.

**Comment by StefanScherer** [comment]
@zoobab We are building rpi-kernel with CircleCI, see circle.yml in this repo. So you can do that as well in a fork. I'm closing this for now as we don't see a high priority adding such a Dockerfile. You still can comment on this issue if you like.
