### ISSUE TITLE
Add support for SPI interface

### ISSUE THREAD

**Issue by vallettea** [hypriot/rpi-kernel#13]
Hello,

thanks for your amazing job!
I noticed that SPI is not enabled and since there is no raspi-conf, how is it possible to activate it ?
thx

**Comment by StefanScherer** [comment]
@vallettea Thanks!

I haven't used SPI yet, but according to the documentation at https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md it could be a kernel module. And this has to be loaded first.

I already use the 4.1.12 kernel of our latest SD image, but earlier versions could also work in a similar way.

You can check our kernel config with

```
modprobe configs
zcat /proc/config.gz | grep CONFIG_SPI
```

And yes, we have CONFIG_SPI=Y and CONFIG_SPI_BCM2835=m and CONFIG_SPI_BCM2708=m.

Try the following on a RPi2:

```
modprobe spi-bcm2835
lsmod
```

If this works you can automatically load this kernel module by adding a line to `etc/modules`, eg with

```
echo spi-bcm2835 >> /etc/modules
```

(All commands some with `root`).

**Comment by vallettea** [comment]
Thanks for your fast reply.
I'll test on the newer version as soon as I'll install it.
Best,
