### ISSUE TITLE
PREEMPT_RT

### ISSUE THREAD

**Issue by PabloGN** [hypriot/rpi-kernel#14]
Could you include real-time kernels by asserting PREEMPT_RT flag
in rpi2_docker_kernel_config as they do in http://docs.emlid.com/Downloads/Real-time-Linux-RPi2/ ?
Is there any drawbacks for this action?
Thank you...

**Comment by PabloGN** [comment]
Well I see, the main problem can be the last verified rt kernel version, i.e., how stable it is. Yet, this is very interesting for many people to have a try.
https://rt.wiki.kernel.org/index.php/Frequently_Asked_Questions
https://rt.wiki.kernel.org/
Thank you again.

**Comment by StefanScherer** [comment]
@PabloGN challenging, but there are kernel patches for 4.1 https://www.kernel.org/pub/linux/kernel/projects/rt/4.1/

But the RPi kernel is derived from raspberrypi/kernel repo and not directly from kernel.org. 
 
A flying Docker Engine would be really cool. With "over the air" updates ;-)

You could try to fork this repo and apply the kernel setting first and build and install this modified kernel. For our small team it is out of scope to do it ourself at the moment.

**Comment by PabloGN** [comment]
Ok, I'll try to `make` it :-)
Thanks...

**Comment by PabloGN** [comment]
Well, I am working on it, I have finished building and the last step is to try it and measure witth "cyclictest". I hope to do the pull request in some days.
Thank you all!!!
