### ISSUE TITLE
Use build matrix at Travis CI

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/rpi-kernel#18]
From https://github.com/hypriot/rpi-kernel/pull/17#issuecomment-172365304

Travis CI: "The job exceeded the maxmimum time limit for jobs, and has been terminated."

To solve this we should try a build matrix to build RPi1 and RPi2 kernel in parallel builds and merge the results into the single DEB file to be deployed to packagecloud Hypriot/rpi.

**Comment by PabloGN** [comment]
The Real Time part should also be built in another instance. See provision.sh from my PR.
RT=1 /vagrant/scripts/compile_kernel.sh

**Comment by StefanScherer** [comment]
Travis CI times out. But Govinda has moved the build to CircleCI. No need to split the build into a build matrix for now.
