### ISSUE TITLE
Add support for Raspberry Pi 3

### ISSUE THREAD

**Issue by hstaudacher** [hypriot/rpi-kernel#19]
Raspberry Pi 3 was released a few days ago: https://www.raspberrypi.org/blog/raspberry-pi-3-on-sale/

I tried to install the latest hypriot (Version 0.6.1 Hector) on it and it doe snot boot. Would be very nice to add support for this.

**Comment by StefanScherer** [comment]
@hstaudacher Congrats. We're still waiting for our order. In the meantime, do you want to test the https://github.com/hypriot/image-builder-rpi/releases/tag/v0.2.5 image?
I don't give much hope that this will boot, but then we have feedback before our boards will arrive.

**Comment by Duvel** [comment]
Hi, I gave the image a try on a new 3, but I only get the pre boot screen with all the colors. Is there anything I could check?

**Comment by hstaudacher** [comment]
Confirmed, just tried it and also only get the colored pre-boot screen.

**Comment by DieterReuter** [comment]
@hstaudacher, @Duvel: you could test the following. Please download the tar file and extract the content to your SD card top folder, it will replace some files. I'm not absolutely sure, if our current Linux kernel will work, but it's worth to try it out.
```
wget https://downloads.hypriot.com/rpi3-bootfiles.tar.gz
gzip -d rpi3-bootfiles.tar.gz
tar xvf rpi3-bootfiles.tar.gz -C <PATH_TO_SDCARD_FOLDER>
```
Content of the tar file are the latest Raspberry Pi bootfiles which supports the RPi 3.
```
-rwxr-xr-x   1 dieter  staff     1494 Mar  2 19:57 LICENCE.broadcom
-rwxr-xr-x   1 dieter  staff    18974 Mar  2 19:57 LICENSE.oracle
-rwxr-xr-x   1 dieter  staff    11120 Mar  2 19:52 bcm2708-rpi-b-plus.dtb
-rwxr-xr-x   1 dieter  staff    10841 Mar  2 19:52 bcm2708-rpi-b.dtb
-rwxr-xr-x   1 dieter  staff    10871 Mar  2 19:52 bcm2708-rpi-cm.dtb
-rwxr-xr-x   1 dieter  staff    12108 Mar  2 19:52 bcm2709-rpi-2-b.dtb
-rwxr-xr-x   1 dieter  staff    12575 Mar  2 19:52 bcm2710-rpi-3-b.dtb
-rwxr-xr-x   1 dieter  staff    17920 Mar  2 19:52 bootcode.bin
-rwxr-xr-x   1 dieter  staff     6481 Mar  2 19:52 fixup.dat
-rwxr-xr-x   1 dieter  staff     2505 Mar  2 19:52 fixup_cd.dat
-rwxr-xr-x   1 dieter  staff     9722 Mar  2 19:52 fixup_db.dat
-rwxr-xr-x   1 dieter  staff     9724 Mar  2 19:52 fixup_x.dat
-rwxr-xr-x   1 dieter  staff  2739672 Mar  2 19:52 start.elf
-rwxr-xr-x   1 dieter  staff   612472 Mar  2 19:52 start_cd.elf
-rwxr-xr-x   1 dieter  staff  4888200 Mar  2 19:52 start_db.elf
-rwxr-xr-x   1 dieter  staff  3840328 Mar  2 19:52 start_x.elf
```

**Comment by Duvel** [comment]
I was able now to boot from the updated SD card and able to login afterwards. It didn't recognize the wifi chip though, but I guess those are other drivers..

**Comment by DieterReuter** [comment]
Congrats! :tophat: 
There is maybe just the WiFi driver missing...

**Comment by DieterReuter** [comment]
@Duvel now you have to start a container, take a screen shot or photo and tweet it on Twitter with something like "first @Docker containers running on a @Raspberry_Pi 3, thanks @HypriotTweets"! :clap:

**Comment by Duvel** [comment]
Done! :)

**Comment by awassink** [comment]
Splendid! Got my Pi 3 running! 

Small instruction issue for the following users:

tar xvf rpi3-bootfiles.tar.gz -C <PATH_TO_SDCARD_FOLDER>

should be:

tar xvf rpi3-bootfiles.tar -C <PATH_TO_SDCARD_FOLDER>

**Comment by DieterReuter** [comment]
@awassink good catch, and I fixed it!

I'm already waiting for my Pi 3's arriving. But now, I'm really happy to help you guys first.

**Comment by Duvel** [comment]
I tried loading the same driver as in raspbian for the wifi chip (firmware-brcm80211) from the non-free repository, but that isn't enough. Any clues where to start?

**Comment by DieterReuter** [comment]
I've just prepared a new beta release of `HypriotOS 0.7.0 Berry` which is based upon an updated 0.6.1 Hector. Feel free to check it out: http://blog.hypriot.com/downloads/.

Features:
* basic support for Raspberry Pi 3 B (internal WiFi/BT is currently not supported)
* Linux kernel 4.1.17
* Docker Engine 1.10.2
* Docker Compose 1.6.2
* Swarm 1.1.3
* btw, it still works on all available Raspberry Pi models (really!)

:whale: :whale: :whale:

**Comment by Govinda-Fichtner** [comment]
I recently build a new kernel that was compatible with RPi3 and is __working__. It is part of our latest build at https://github.com/hypriot/image-builder-rpi

**Comment by Duvel** [comment]
Just installed the latest build and had no issues running it and running my stuff on it! I got hostapd running on wlan0, perfect!

**Comment by jmMeessen** [comment]
I am a little confused. Where can find the compiled image ? I am interested to try it as the Hypriot image of begin March failed to boot (MMC errors) on my two RPi3.

**Comment by Duvel** [comment]
Hi, you can find it at the releases page: https://github.com/hypriot/image-builder-rpi/releases.

**Comment by jmMeessen** [comment]
Thanks. I overlooked the location.

I couldn't make it to test the image tonight. Will try tomorrow.

**Comment by jmMeessen** [comment]
I finally got around to test this release candidate with my mis-behaving RPi3.

I can confirm that I don't have the MMC reader error anymore and that this image (https://github.com/hypriot/image-builder-rpi/releases/download/v0.4.4/sd-card-rpi-v0.4.4.img.zip) is functional.

**Comment by jmMeessen** [comment]
Ooops. Just seen that the issue has been marked as closed.

**Comment by StefanScherer** [comment]
@jmMeessen Thanks for the feedback!
Yes, the rpi-kernel issue is solved as the kernel build is also for RPi3.
Please follow the image-builder-rpi repo for further updates ;-)

**Comment by StefanScherer** [comment]
(And yes, we're cleaning our Waffle board)
