### ISSUE TITLE
rpi-update removes hypriot kernel

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/rpi-kernel#3]
Issue from Gitter @fmatejic:

Hi, I used `rpi-update` on HypriotOS. This was a mistake ... Do you have some howto how to patch kernel, or some notes for revert back normal state ?

```
HypriotOS: root@home in /etc/init.d
$ /etc/init.d/docker status
[FAIL] Docker is not running ... failed!
cat /var/log/docker.log | grep fatal
time="2015-05-23T23:22:41+02:00" level=fatal msg="Shutting down daemon due to errors: error intializing graphdriver: driver not supported"
$ uname -a
Linux home 3.18.14-v7+ #792 SMP PREEMPT Sat May 23 16:19:32 BST 2015 armv7l GNU/Linux
```

Thanks

**Comment by arnulfojr** [comment]
Hi, I've used today the `rpi-update` and after I ran `uname -a` and it removed the hypriot kernel, is it normal? How safe is it? is not safe? My RPI is running normally so far but unsure of the side effects.

https://github.com/hypriot/image-builder-rpi/issues/256
