### ISSUE TITLE
can we make it easier to correlate releases and their files?

### ISSUE THREAD

**Issue by SvenDowideit** [hypriot/rpi-kernel#33]
I see there's a new release tag here on github - but it doesn't link to where the pre-build files are - ie https://packagecloud.io/Hypriot/rpi/?filter=debs

and when I go there, the files don't reference the kernel version or release tag

if each GH release listed the url's to its artifacts, that would help alot - for my use in RancherOS, uploading the non-debian package files to the GH release would make it even simpler :)

**Comment by StefanScherer** [comment]
The new kernel 4.4.43 should be in packagecloud as we use it in the latest image-builder-rpi release https://github.com/hypriot/image-builder-rpi/commit/f18bfabee75a60c4dc62c5abdc5badcc784d7f8f
The RPi specific packages are in https://packagecloud.io/Hypriot/rpi

**Comment by StefanScherer** [comment]
Well, our compile script runs on Circle and produces these build artifacts (eg. in build https://circleci.com/gh/hypriot/rpi-kernel/44):

```
+ ls -lh /home/ubuntu/rpi-kernel/output/20170319-133405
total 118M
-rw-rw-r-- 1 ubuntu ubuntu   41 Mar 19 14:51 kernel-commit.txt
-rw-r--r-- 1 ubuntu ubuntu 822K Mar 19 14:51 libraspberrypi0_20170319-133405_armhf.deb
-rw-r--r-- 1 ubuntu ubuntu 325K Mar 19 14:51 libraspberrypi-bin_20170319-133405_armhf.deb
-rw-r--r-- 1 ubuntu ubuntu 387K Mar 19 14:51 libraspberrypi-dev_20170319-133405_armhf.deb
-rw-r--r-- 1 ubuntu ubuntu  30M Mar 19 14:51 libraspberrypi-doc_20170319-133405_armhf.deb
-rw-r--r-- 1 ubuntu ubuntu 177K Mar 19 14:51 linux-firmware-image-4.4.50-hypriotos+_4.4.50-hypriotos+-2_armhf.deb
-rw-r--r-- 1 ubuntu ubuntu 178K Mar 19 14:51 linux-firmware-image-4.4.50-hypriotos-v7+_4.4.50-hypriotos-v7+-1_armhf.deb
-rw-r--r-- 1 ubuntu ubuntu 6.9M Mar 19 14:51 linux-headers-4.4.50-hypriotos+_4.4.50-hypriotos+-2_armhf.deb
-rw-r--r-- 1 ubuntu ubuntu 6.9M Mar 19 14:51 linux-headers-4.4.50-hypriotos-v7+_4.4.50-hypriotos-v7+-1_armhf.deb
-rw-r--r-- 1 ubuntu ubuntu  15M Mar 19 14:51 linux-image-4.4.50-hypriotos+_4.4.50-hypriotos+-2_armhf.deb
-rw-r--r-- 1 ubuntu ubuntu  15M Mar 19 14:51 linux-image-4.4.50-hypriotos-v7+_4.4.50-hypriotos-v7+-1_armhf.deb
-rw-r--r-- 1 ubuntu ubuntu 779K Mar 19 14:51 linux-libc-dev_4.4.50-hypriotos+-2_armhf.deb
-rw-r--r-- 1 ubuntu ubuntu 779K Mar 19 14:51 linux-libc-dev_4.4.50-hypriotos-v7+-1_armhf.deb
-rw-r--r-- 1 ubuntu ubuntu 3.4M Mar 19 14:51 raspberrypi-bootloader_20170319-133405_armhf.deb
-rw-r--r-- 1 ubuntu ubuntu  26M Mar 19 14:51 raspberrypi-kernel_20170319-133405_armhf.deb
-rw-r--r-- 1 ubuntu ubuntu  14M Mar 19 14:51 raspberrypi-kernel-headers_20170319-133405_armhf.deb
```

You can send us a pull request with a suggestion what you need in the GH releases. Circle also can deploy to GH releases.

**Comment by StefanScherer** [comment]
We have a new kernel 4.9.80, and the deb files at GitHub releases https://github.com/hypriot/rpi-kernel/releases/tag/v4.9.80

With our next release of HypriotOS 1.8.0 we only replace the raspberrypi-kernel and optionally the raspberrypi-kernel-headers package. We use the bootloader and other things from upstream Raspbian LITE 2018-03-13.

**Comment by StefanScherer** [comment]
Added `ghr` to the release deployments.
