### ISSUE TITLE
Vagrant build of "upgrade-kernel-to-4.4.27"

### ISSUE THREAD

**Issue by RabGitHub** [hypriot/rpi-kernel#34]
Looking to rebuild Hypriot kernel "upgrade-kernel-to-4.4.27" via Vagrant:-
    git clone --branch upgrade-kernel-to-4.4.27  https://github.com/hypriot/rpi-kernel.git
    cd rpi-kernel
    vagrant up

The build fails at this point...
    ==> docker-raspbian: + git clone --depth 20 https://github.com/raspberrypi/linux.git /var/kernel_build/cache/linux-kernel
...
    ==> docker-raspbian: Checking out files: 100% (52748/52748), done.
...
    ==> docker-raspbian: + git checkout -qf 1c8b82bcb72f95d8f9d606326178192a2abc9c9c
    ==> docker-raspbian: fatal: reference is not a tree: 1c8b82bcb72f95d8f9d606326178192a2abc9c9c

s the depth too restricted for the 4.4.27 version of the Kernel?

I tried going into the Vagrant Virtualbox and increasing the depth, but still couldn't get this to work:-
    vagrant ssh
    mkdir /tmp/tmp
    cd /tmp/tmp
    git clone --depth 100 https://github.com/raspberrypi/linux.git
    cd linux/
    git checkout -qf 1c8b82bcb72f95d8f9d606326178192a2abc9c9c
    fatal: reference is not a tree: 1c8b82bcb72f95d8f9d606326178192a2abc9c9c

Does anyone have any suggestions on how to resolve, or an alternative approach to rebuilding Hypriot kernel using 4.4.27 Linux kernel?

Thanks in advance.

**Comment by brainstorm** [comment]
That message is telling you that the hash commit is not within the `git clone --depth 100` "release window".

If you want to compile that specific kernel, you could just remove the `--depth 100` argument from the `git clone` above (present in the `scripts/compile_kernel.sh`) and run `vagrant provision`.

Please note that cloning all the linux kernel history can take a while and fill quite a bit of unnecessary history in your disk.

Hope that helps!

**Comment by StefanScherer** [comment]
Fixed with latest commit in master.
