### ISSUE TITLE
Kernel 4.14.70 not present in packagecloud.io/hypriot/rpi

### ISSUE THREAD

**Issue by rtrox** [hypriot/rpi-kernel#48]
I see that 4.14.70 has been built and exists as a release on github, but it doesn't appear that it's been uploaded to the hypriot repos (packagecloud.io/hypriot/rpi).

I checked the CircleCI config, and it does appear that CI should be uploading new releases. Is this release intentionally excluded from the repos? Or did CircleCI fail?

I need at least 4.14.50 to pull in the vxlan issue referenced in https://github.com/raspberrypi/linux/issues/2580 . I can pull the .debs manually from github, but I would feel more comfortable updating from the repos.

**Comment by rtrox** [comment]
Awesome, thanks for the response. Expecting reflashes is totally reasonable, especially given the cloud-like use case (though they do stress the ad cards).  I'll play with with the build artifacts on Travis until a new SD card image is pushed.

Thanks!

**Comment by StefanScherer** [comment]
Should be fixed with #49, I've triggered a build with 4.14.79
