### ISSUE TITLE
Arm64?

### ISSUE THREAD

**Issue by bd8392** [hypriot/rpi-kernel#56]
Will there be an ARM64 version of hypriot? (They have slightly more docker images)

**Comment by firecyberice** [comment]
Please have a look here: https://github.com/DieterReuter/rpi64-kernel

**Comment by DieterReuter** [comment]
Or even better and more current, look at using Ubuntu 64bit for the Raspberry Pi, works great so far!

**Comment by bd8392** [comment]
Okay thanks :-)

**Comment by bd8392** [comment]
@DieterReuter is there also a version vor RPI4? @themaintainersofhypriot -> If this is stable, can you mke a post in your blog for everyone who wants this enabled by default with cloud-config? Would be a major improvement for me =)
