### ISSUE TITLE
BUILD_GROUP is known via whoami?

### ISSUE THREAD

**Issue by zoobab** [hypriot/rpi-kernel#8]
Hi,

I am trying to rebuild the kernel by calling directly the build script because I cannot have vbox where I build the kernel.

Is there a reason why you use the whoami command to identify the group of the user?

    else
      # running in drone build
      SRC_DIR=`pwd`
      BUILD_USER=`whoami`
      BUILD_GROUP=`whoami`
    fi

I am forced to modify your script and to put the grp of the user by hand because I cannot find a good way to automate it.

**Comment by StefanScherer** [comment]
@zoobab that was the way it worked for us to build it in our CI.
Could you try `id -u -n` and `id -g -n` and let me know if it works for you.

**Comment by zoobab** [comment]
Yes those 2 commands works for me. Thx!

I have added ccache option as well to the script, if you are interested...

**Comment by StefanScherer** [comment]
Yes, send us a PR :+1:
